### ISSUE TITLE
. and ! mappings apparently do nothing...

### ISSUE THREAD

**Issue by giddie** [tpope/vim-vinegar#113]
I can't figure out what I'm doing wrong here - I've commented out my entire .vimrc, except for vim-plug and vinegar, but in netrw, pressing `.` or `!` seems to do nothing at all. Pressing `!` twice in succession causes `:.!` to appear in the command, but this appears to be a global binding, not specific to netrw.

**Comment by tpope** [comment]
I don't know, I think it might require `filetype plugin on`?

**Comment by giddie** [comment]
Here's the `.vimrc` I'm using to test:

```vim
filetype plugin indent on

call plug#begin('~/.vim/vim-plug')
Plug 'dhruvasagar/vim-vinegar'
call plug#end()
```

The `-` binding works fine: takes me into netrw. However, the `.` and `!` bindings do nothing when I have a file highlighted in netrw. I've tried in both `nvim 0.4.2` and `vim 8.1 1-2102`. I'm on Archlinux.

**Comment by giddie** [comment]
Sorry, totally my fault: I missed that I was using a fork of this plugin intended to work better with NERDtree, so no surprises it's not playing well with netrw :p All is well now, and I apologise for the noise.
