### ISSUE TITLE
vim-vinegar pollutes numbered register history when using '-'

### ISSUE THREAD

**Issue by andrewferrier** [tpope/vim-vinegar#120]
I have seen an issue for some time where spurious entries get inserted into the numbered registers in vim, and I just realized that (it seems) it's `vim-vinegar` which is doing it, when moving 'up' through directories.

Observed behaviour/recreation instructions:

* Install a recent version of vim (I'm using VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 09 2021 23:51:55) Included patches: 1-2489, Compiled by Arch Linux). However, I've also seen this happen with NeoVim 0.5 too. Doesn't seem to be that version-specific.

* Empty out ~/.vim/

* Clone `vim-vinegar` into ~/.vim/pack/pack/start/.

* Start vim with a scratchpad text file containing some existing content.

* Move to any line, and delete it using `dd`.

* Save the file with `:w`. Type `:registers` and observe that the deleted line is in the `"1` register.

* Press `-` to have vim-vinegar navigate to the containing directory.

* Type `:registers` and observe that the the value has been pushed down to the `"4` register. `"1` now contains `../`, `"2` now contains `./`, `"3` is now empty.

Expected behaviour:

* Registers should not be touched by navigating through directories.

Thanks for all your great work on `vim-vinegar` and the other plugins you maintain. I use them daily!

**Comment by tpope** [comment]
I see this on `:e %h` too. It's netrw. (It's always netrw.)
