### ISSUE TITLE
can't disable grouping by suffix

### ISSUE THREAD

**Issue by bart9h** [tpope/vim-vinegar#121]
When I press `S` in the netrw window to edit the sorting sequence, and replace the value with just `*`, it does nothing.
If I press `S` again the old default value is shown.

If I disable vinegar, it works.

**Comment by tpope** [comment]
Fugitive took over maintaining this option in #94 (discussion in #71). I hadn't considered that it would prevent manual override. @kiryph thoughts? Your proposed `OptionSet` solution is enticing. `v:option_old` can be used to derive if the sort sequence has been manually overridden, and if so, bail.
