### ISSUE TITLE
I love vim-vinegar. Is it possible to use it to navigate the file system, and exit to a bash shell in the same location?

### ISSUE THREAD

**Issue by teddyknox** [tpope/vim-vinegar#123]
I tried `set autochdir` and had no luck.

**Comment by teddyknox** [comment]
Also seeing this https://vi.stackexchange.com/questions/5475/use-netrw-to-change-my-bash-working-directory

**Comment by tpope** [comment]
Vim is running _inside_ bash. Nothing you do inside it can affect bash's working directory.
