### ISSUE TITLE
VinegarUp occasionally hangs Neovim in VM

### ISSUE THREAD

**Issue by pcewing** [tpope/vim-vinegar#124]
Versions:
```
neovim: v0.4.4
vim-vinegar: b245f3a
OS: Ubuntu 20.04 (VirtualBox guest)
```

I'm running Neovim in an Ubuntu 20.04 VirtualBox guest and using `-` to traverse to the parent directory occasionally causes a hang that persists until pressing `ctrl-C`. I experience this something like 30-50% of the time.

I was able to track down the long running command to this line:
https://github.com/tpope/vim-vinegar/blob/9cfea73481dc1c1d8edc3ff6f5cd89173fe2996d/plugin/vinegar.vim#L57

I'm actually able to reproduce the issue now just by issuing the following:
`:execute 'edit' '%:h'`

This makes me think that it may not be vinegar at all but something in how `edit` behaves? The VM is beefy so I'm confident it's not a resource constraint. Even though this may not be an issue with vinegar, I thought I'd start here as I haven't dug into vimscript much before and was hoping someone might point me in the right direction.

Edit: Just noticed that even just running `nvim .` from home directory causes the same hang so I'm now convinced this has nothing to do with `vim-vinegar`. Going to leave this open for the time being just in case anyone has thoughts on where I might get started investigating.

**Comment by tpope** [comment]
I agree this doesn't look like a Vinegar bug, but you should still try with Vinegar uninstalled because it might be tickling a netrw bug with one of the netrw options it sets. If that fixes it, you can try commenting out the various `let g:netrw_...` lines in `plugin/vinegar.vim` to find the culprit.

**Comment by pcewing** [comment]
Yep, it's reproducible even when running vim without loading my `vimrc` at all. I tried updating to the Neovim v0.5.0 nightly build and can't reproduce it there so perhaps this was actually already fixed. Will see if I can track down an issue for it. Thanks!
