### ISSUE TITLE
VinegarUp brings up nerdtree when nerdtree exists?

### ISSUE THREAD

**Issue by huangzonghao** [tpope/vim-vinegar#125]
I love `netrw`'s swiftness and in-place file opening, while at the same time I want to enjoy the robust tree view of `nerdtree` (the tree view of `netrw` is too buggy on my machine). So I just added `nerdtree` to my vim/bundle (I am using pathogen - thanks Tim!). But to my surprise `VinegarUp` immediately starts to brings up `nerdtree` instance whenever called, instead of `netrw` -- I even haven't reloaded my vim yet! And `Ctrl-^` no longer works -- this may not be a surprise, since I am effectively calling it inside `nerdtree`. So is expected behavior? And how can I set `VinegarUp` back to use `netrw`?

**Comment by tpope** [comment]
```vim
let g:NERDTreeHijackNetrw = 0
```
