### ISSUE TITLE
Feature Request: Group empty directories

### ISSUE THREAD

**Issue by pheeria** [tpope/vim-vinegar#126]
Hi 🖖

Drew Neil's wisdom regarding oil and vinegar only started to make sense after having used your plugin. Thanks for it!

What would be really nice if vinegar could add a feature flag to enable grouping/nesting empty directories, so that Java development (I know, probably it's better just to quit Java) becomes bearable, so that `java/com/bubble/my/**` is one `Enter` away and not four.

I tried using Nvim-Tree because of this feature, however using drawers feels weird now.

Similar implementation:
Issue: kyazdani42/nvim-tree.lua#191
Feature PR: kyazdani42/nvim-tree.lua#247

**Comment by tpope** [comment]
This is a change that would need to happen on the netrw side of things. Vinegar is little more than a few bolted-on maps and some tweaks to netrw options. I like the idea, but can't speak to whether it would gain traction upstream.
