### ISSUE TITLE
Icon support

### ISSUE THREAD

**Issue by pynvimdev** [tpope/vim-vinegar#128]
vim-vinegar is supposed to make netrw like a modern browser for vim. So icon support for vim-vinegar would be appreciated

**Comment by Ashvith10** [comment]
If you're interested, you should take a look into [this discussion](https://github.com/ryanoasis/vim-devicons/issues/272)

**Comment by tpope** [comment]
Yeah, I will not be taking ownership of any icon code, try there instead.
