### ISSUE TITLE
Recursively Delete Directories

### ISSUE THREAD

**Issue by unrealapex** [tpope/vim-vinegar#133]
It would be nice to have the ability to recursively delete directories in Netrw. I think it would be a good addition to Vinegar because most modern file managers for Vim have this feature and Netrw itself does not include it. @tpope do you think Bram might accept this feature? Shall I attempt to file an issue in the Vim repository?

**Comment by tpope** [comment]
I would email the maintainer of netrw, Charles E. Campbell, about it. That's not something I would want to take responsibility for in Vinegar.

**Comment by unrealapex** [comment]
I understand. It appears other users have asked about this feature. His reason for not implementing is the possibility of accidental folder deletion. His concern is understandable but it seams irrelevant considering there is a prompt.
