### ISSUE TITLE
For some reason ~ is not mapped

### ISSUE THREAD

**Issue by marlun** [tpope/vim-vinegar#135]
`-` is working however `~` just does the normal function (switch case) and looking at the vinegar source code I can't see a reason for it not to be mapped.

:verbose nmap `-` gives:
```
n  -             <Plug>VinegarUp                                                                                                                                                       
        Last set from ~/.local/share/nvim-new/lazy/vim-vinegar/plugin/vinegar.vim line 32
```

:verbose nmap `~` gives:
```
No mapping found
```

I've tried with with minimal setup:

```vim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
  "tpope/vim-vinegar",
})
```

**Comment by tpope** [comment]
```
-                       Open the parent directory of the current file.  This
                        is the only mapping available outside of netrw
                        buffers.
```

The takeaway from this is that other maps like `~` are *not* available outside netrw buffers.

The entirety of the `~` map is `:edit ~/<CR>`, so it's very easy to do it yourself globally if that's what you want.

**Comment by marlun** [comment]
Ah, thanks! Yes it was not a hard mapping to do on your own, I was just wondering why it didn't work and missed that fact.
