### ISSUE TITLE
Repeat command (`.`) breaks when used over SCP

### ISSUE THREAD

**Issue by dctucker** [tpope/vim-vinegar#140]
### Steps to reproduce

1. Load a file via SCP
2. `:Vex` and select another file and then press `<CR>`.
3. `Vyp` to duplicate current line.
4. `.` to duplicate current line again. **Notice user is sent to `:` command mode with the SCP URL and paste buffer preloaded.**

### Expected behaviour

1. Initial file is loaded via SCP.
2. Split, browse, second file loads with syntax highlighting enabled.
3. Current line is duplicated.
4. Repeat command duplicates the line again.

### Version of Vim

9.1.727

### Notes

Having originally assumed this was breakage in vim/vim, I've narrowed down the odd behavior to this plugin, and I'm able to get repeat functionality working as normal by commenting out the lines in `vinegar.vim` that run variations of `map <buffer> .`. Somehow the effect of these map commands leak into the edit buffer after a file is loaded. While I can survive without having this plugin's `.` functionality, other users who do rely on it may be similarly inconvenienced, so I figured opening an issue would be a good idea.

**Comment by tpope** [comment]
When I follow these instructions, the file buffer I end up with has an `netrw` file type. This means Vinegar's maps get created, but it also means 100 other things are wrong, most notably, the syntax highlighting. Smells like a netrw bug to me.

**Comment by dctucker** [comment]
Linking this here for posterity https://github.com/vim/vim/issues/15958. I'll probably need to open another issue to get the gears moving on a fix.
