### ISSUE TITLE
doc?

### ISSUE THREAD

**Issue by jtmkrueger** [tpope/vim-vinegar#24]
Any plans to make a `:help` doc for this? 

If not, would you consider a pull request?

**Comment by kiryph** [comment]
I have written a doc file for vinegar at https://github.com/kiryph/vim-vinegar/blob/master/doc/vinegar.txt.

@tpope if you like it as a starting point for your repository, feel free to use it.

**Comment by spinningarrow** [comment]
It would be great to have a doc file; I didn't even know about `!`, `.` and the other functionality until today (and I've been using this for a couple of years). Perhaps @tpope would be willing to accept a PR from ^ as a starting point?
