### ISSUE TITLE
Duplicate entry issue

### ISSUE THREAD

**Issue by keith** [tpope/vim-vinegar#27]
It wouldn't surprise me if this was totally my fault but I'm seeing an issue where multiple lines appear for the same file in a directory. Here is a short video of what I'm seeing.

http://cl.ly/V56E

You can see the function I'm calling for the setup on the left. I also have some possible relevant automatic window sizing options (although removing these doesn't help):

```
set winwidth=80
set winminwidth=20
set winheight=7
silent! set winminheight=7
set winheight=999
```

([the rest of my vimrc](https://github.com/Keithbsmiley/dotfiles/blob/master/vimrc#L424-L432))

**Comment by netei** [comment]
I was able to reproduce with the following .vimrc : 

```
set nocompatible
set hidden
call plug#begin()
Plug 'tpope/vim-vinegar'
call plug#end()
```

then do : `mkdir -p /tmp/a/dir/ectory && touch /tmp/a/dir/ectory/test.txt && vim /tmp/a/dir`

and hit `<enter>` twice to open the file, hit `<minus>` to go up to the directory and there you see the filename is present twice.
