### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by juanghurtado** [tpope/vim-vinegar#38]
Hi there!

I know it is a strange question, but I'm getting crazy so I must ask: Is there something in Vinegar that may set `nonumber` on its buffer? I can't remember when, but at some point my Vinegar screens stopped having line numbers on, and I can't find where they are being disabled.

Of course my `.vimrc` has `set number`, and a quick `grep` on my doftiles doesn't reveal any `nonumber` over there.

**Comment by kiryph** [comment]
Use `let g:netrw_bufsettings = 'noma nomod nu nowrap ro nobl'` in your vimrc.
