### ISSUE TITLE
vinegar forgets which pane it's in

### ISSUE THREAD

**Issue by achin** [tpope/vim-vinegar#39]
I'm using vinegar with MacVim 7.3. It seems like vinegar forgets which pane it's supposed to work in when switching back and forth between multiple panes. When this happens, the file browser opens in the proper pane, but some other pane becomes the active one and set to read-only.

I can reliably reproduce this behavior with MacVim 7.3, but not with the regular command-line version. Steps to reproduce:

1. Start a new vim instance: `mvim`
1. Create a new pane: `:vsp`
1. Use vinegar to open a file: `-<CR>`
1. Switch to the other (left) pane: `<C-w>h`
1. Open vinegar: `-`
1. *Expected result*: vinegar opens in the left pane, the cursor is in the left pane, and the left pane is set to read-only
1. *Result*: vinegar opens in the left pane, but the cursor is in the right pane, and both the left and right panes are set read-only

Please let me know if there's any other information I can provide. Thanks for the great plugin!

**Comment by srustamo** [comment]
I have the same problem. Running `:e %:h` displays the same problematic behavior. Also, `w-l` or `w-h` don't move the cursor to the other split. 

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 14 2016 11:37:19)
MacOS X (unix) version
Included patches: 1-979
Compiled by Homebrew
Huge version without GUI.

**Comment by tpope** [comment]
It's a netrw bug
