### ISSUE TITLE
Copying of "../" to clipboard

### ISSUE THREAD

**Issue by janko** [tpope/vim-vinegar#40]
I use `clipboard=unnamed` in my vim configuration, because I want system and "vim" clipboard to be the same. What happens often is that I yank a part of text, press `-` and navigate to some other file, and paste the yanked content.

The problem is that, when I press `-`, then "`../`" is somehow being yanked also, and then it overrides what I had in clipboard. Is there a way to avoid that in the implementation?

**Comment by aleprovencio** [comment]
I'm getting this with 'clipboard=unammedplus' upon calling ':edit .' from a
loaded buffer.

The issue does not happen when vinegar is disabled. Do you guys have any updates on this?

**Comment by tpope** [comment]
Just tried and it happens for me disabled, albeit it's an empty string rather than `..`. This is netrw making use of `:delete` and haphazardly restoring the unnamed register rather than just using `:delete _` to avoid clobbering it to begin with.

**Comment by aleprovencio** [comment]
@tpope , are you on netrw v154?

**Comment by tpope** [comment]
As it happens I am on v147g, which is what I guess I upgraded to last time it has an issue. Maybe since then the blank line clobber has fixed, but that doesn't change my other assertion.
