### ISSUE TITLE
Alternate keymap

### ISSUE THREAD

**Issue by dghgonzalez** [tpope/vim-vinegar#43]
Hi i am using vim on arch linux with bépo keymap (french dvorak) and i cannot get vinegar to start at all (and i tried the new mapped key for '-' ).
The script can be found at http://bepo.fr/wiki/Vim under the section "Reconfiguration totale des touches" (not present in the hypertext menu).

**Comment by dghgonzalez** [comment]
Sorry for my lack of responsiveness.
The :map - throws:
   -           * 8
and 8 is the key it is supposed to be mapped to.

**Comment by PaBLoX-CL** [comment]
It seems that the comment was automatically formatted, maybe surround it with backticks (`).

**Comment by dghgonzalez** [comment]
Sorry again
`   -           * 8`

**Comment by mjacobus** [comment]
I also would love to have mapping customized.

`-` has a vim built in feature that gets overwritten by vinegar.

```
-  <minus>		[count] lines upward, on the first non-blank
			character |linewise|.
```

**Comment by Blake-LeBlanc** [comment]
Any update on this? As @mjacobus pointed out, `-` can be really handy with relative line movements. Being able to set vinegar to, say, `_` would help alleviate this collision.

Thanks again for your great plugins, Tim!

**Comment by tpope** [comment]
`<Plug>` maps are supported, and it won't override an existing `-` map.
