### ISSUE TITLE
Excluding .gitignore contents

### ISSUE THREAD

**Issue by jacobthemyth** [tpope/vim-vinegar#48]
This might not be the right place to discuss this, if not, feel free to just close this.

I am trying to exclude the contents of my .gitignore from netrw, so I thought I'd stick them in wildignore, but the format of wildignore is fairly different from .gitignore, so I ended up doing the following to include trailing slashes and unescape the leading dots. I'm not even 100% sure I want to have all my .gitignore contents in wildignore (sometimes I do actually want to edit them), but I'm willing to try it out for a while, so I was wondering if this seems like a crazy way to go about getting it to work with vinegar. Thanks!

```vim
let &wildignore = join(map(split(substitute(
  \ netrw_gitignore#Hide(), '\\.', '.', 'g'), ','), "v:val.','.v:val.'/'"), ',')
```

**Comment by RichardDooling** [comment]
I wanted to do the same thing (namely hide .gitignore files). I don't know vimscript, but I'm trying to learn. So I must guess at what the functions do herein (when I learn vimscript maybe I'll try to add some comments), but in the meantime I just added netrw_gitignore#Hide() into the netrw_list_hide string using dot connectors as follows

let g:netrw_list_hide =
      \ join(map(split(&wildignore, ','), '"^".' . s:escape . '. "$"'), ',') . ',^\.\.\=/\=$' . netrw_gitignore#Hide() . (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles)-1:-1] ==# s:dotfiles ? ','.s:dotfiles : '')

You can search on netrw_gitignore#Hide() and see what it's supposed to do, but it has to be added in vim-vinegar or in an "after" file. It won't work if you try to add it to .vimrc.

Rick

**Comment by Hotschke** [comment]
I have modified the code to `set wildignore` from `netrw_gitignore#Hide()` from @jacobthemyth  because it was not vinegar was not hiding `*.pyc` files:
It works for me with following:
````
let &wildignore = join(map(split(substitute(substitute(
  \ netrw_gitignore#Hide(), '\.\*', '*', 'g'), '\\.', '.', 'g'), ','), "v:val.','.v:val.'/'"), ',')
````

`<C-r>=&wildignore` gives
```
.DS_Store,.DS_Store/,._.DS_Store,._.DS_Store/,.Spotlight-V100,.Spotlight-V100/,.*.swp,.*.swp/,.*.swo,.*.swo/,tags,tags/,*.pyc,*.pyc/,*.orig,*.orig/,*~,*~/
```
I am not sure whether I need the copies of each entry with an additional slash at the end.

**Comment by juanghurtado** [comment]
I can't get netrw ignore stuff from the `.gitignore` file.

My scenario is: vim-vinegar + netrw from eiginn/netrw

I've tried all suggested solutions on this thread, plus the instructions from `netrw_gitignore.vim` file under eiginn/netrw (`let g:netrw_list_hide = netrw_gitignore#Hide()`), but no luck. Content excluded in .gitignore files is being shown in netrw.

My goal is to be able to use netrw `:Explore` command without having ignored content being shown in the results.

**Comment by kiryph** [comment]
@juanghurtado 
You can try following patch for vinegar:

```diff
❯ git diff
diff --git a/plugin/vinegar.vim b/plugin/vinegar.vim
index 7de6685..b1f2fd2 100644
--- a/plugin/vinegar.vim
+++ b/plugin/vinegar.vim
@@ -21,7 +21,8 @@ let s:dotfiles = '\(^\|\s\s\)\zs\.\S\+'
 let s:escape = 'substitute(escape(v:val, ".$~"), "*", ".*", "g")'
 let g:netrw_list_hide =
       \ join(map(split(&wildignore, ','), '"^".' . s:escape . '. "/\\=$"'), ',') . ',^\.\.\=/\=$' .
-      \ (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles)-1:-1] ==# s:dotfiles ? ','.s:dotfiles : '')
+      \ (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles):-1] ==# s:dotfiles ? ','.s:dotfiles : '') .
+      \ ','.netrw_gitignore#Hide()
 if !exists("g:netrw_banner")
   let g:netrw_banner = 0
 endif
@@ -97,6 +98,12 @@ function! s:escaped(first, last) abort
 endfunction

 function! s:setup_vinegar() abort
+  if exists("w:netrw_wigkeep")
+    let g:netrw_list_hide =
+            \ join(map(split(w:netrw_wigkeep, ','), '"^".' . s:escape . '. "$"'), ',') . ',^\.\.\=/\=$' .
+            \ (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles):-1] ==# s:dotfiles ? ','.s:dotfiles : '') .
+            \ ','.netrw_gitignore#Hide()
+  endif
   if empty(s:netrw_up)
     " save netrw mapping
     let s:netrw_up = maparg('-', 'n')
```

However, the helper function `netrw_gitignore#Hide()` is quite slow. This means opening a netrw window is now laggy!

You could do it only once on vim startup which means only
- global gitignore
- or if your startup directory is the project dir with the folder `.git`

are ignored:
```diff
❯ git diff
diff --git a/plugin/vinegar.vim b/plugin/vinegar.vim
index 7de6685..b1f2fd2 100644
--- a/plugin/vinegar.vim
+++ b/plugin/vinegar.vim
@@ -21,7 +21,8 @@ let s:dotfiles = '\(^\|\s\s\)\zs\.\S\+'
 let s:escape = 'substitute(escape(v:val, ".$~"), "*", ".*", "g")'
 let g:netrw_list_hide =
       \ join(map(split(&wildignore, ','), '"^".' . s:escape . '. "/\\=$"'), ',') . ',^\.\.\=/\=$' .
-      \ (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles)-1:-1] ==# s:dotfiles ? ','.s:dotfiles : '')
+      \ (get(g:, 'netrw_list_hide', '')[-strlen(s:dotfiles):-1] ==# s:dotfiles ? ','.s:dotfiles : '') .
+      \ ','.netrw_gitignore#Hide()
 if !exists("g:netrw_banner")
   let g:netrw_banner = 0
 endif
```
I am still interested in a faster solution for myself. Random thoughts are:
- use an event from fugitive which scans for .git
- use other plugin with faster gitignore detection (haven't check anything; one could start with https://www.vim.org/scripts/script.php?script_id=2557)

**Comment by kiryph** [comment]
My solution of my previous comment is IMHO really slow!
```
❯ vim --startuptime vim-startup.log -c ":q"
❯ grep 'netrw\|vinegar' vim-startup.log
035.224  001.100  001.100: sourcing /Users/kiryph/.vim-configs/main/pack/manual/start/netrw/plugin/netrwPlugin.vim
119.506  000.366  000.366: sourcing /Users/kiryph/.vim/pack/manual/start/netrw/autoload/netrw_gitignore.vim
1240.912  1122.736  1122.370: sourcing /Users/kiryph/.vim-configs/main/pack/minpac/start/vim-vinegar/plugin/vinegar.vim
1385.178  000.027  000.027: sourcing /Users/kiryph/.vim/pack/minpac/start/vim-vinegar/plugin/vinegar.vim
1398.031  000.048  000.048: sourcing /Users/kiryph/.vim/pack/manual/start/netrw/plugin/netrwPlugin.vim
1401.556  000.239  000.239: sourcing /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
```

You should ignore it!.

**Comment by syphar** [comment]
For the people using plugins: 

there is a [plugin](https://www.vim.org/scripts/script.php?script_id=2557) that sets `wildignore` based on a `.gitignore` file.
