### ISSUE TITLE
Vinegar main keybind

### ISSUE THREAD

**Issue by juanghurtado** [tpope/vim-vinegar#5]
I don't consider this an issue as is, but vim-vinegar main keybind (`-` key) conflicts with netrw `-` key, which is used to go up one directory.

As vinegar hides `../` links on the list, you have to press `a` a couple of times to get those `../` back in order to be able to use them. With netrw `-` key you could go up one directory with a single keystroke.

**Comment by srustamo** [comment]
Sorry for resurrecting the closed issue, I also see `"./" Illegal file name`, but only on first press of <kbd>-</kbd>. After this it does not show up. Also, noticed that running `vim e.` and from here pressing <kbd>-</kbd> does not give the error. 

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 28 2015 12:57:24)
MacOS X (unix) version
Included patches: 1-936
Compiled by Homebrew

List of plugins installed:

HyperList
SyntaxRange
ag
calendar.vim
ctrlp.vim
dbext_2000
indentLine
loremipsum
matchit
minivimrc
rainbow_parentheses.vim
restore_view.vim
syntastic
tagbar
taglist_46
utl.vim
vim-airline
vim-commentary
vim-diminactive
vim-dokumentary
vim-fontsize
vim-fugitive
vim-gtfo
vim-numbertoggle
vim-orgmode
vim-qargs
vim-sensible
vim-speeddating
vim-surround
vim-unimpaired
vim-vinegar
vimroom
vimux

**Comment by srustamo** [comment]
Check the same setup on the same machine but with MacVim and get no error.

**Comment by srustamo** [comment]
Correct the previous: opening a file with `mvim` and hitting <kbd>-</kbd> fort the first time gives the error.
