### ISSUE TITLE
Prevent "-" from hopping up directory in git-status buffer from fugitive

### ISSUE THREAD

**Issue by iamdionysus** [tpope/vim-vinegar#56]
First of all, I really appreciate your great work. My vimrc has so many
tpope now. Because of that, now I have one minor issue and I'd like to ask
you first before I make any changes as your guideline. 

When I bring up `git-status` buffer from `:Gstatus` using fugitive, `-` will
do either `:Git add` or `:Git reset`. However, when I have `vim-vinegar`,
  `-` brings directory as you promised in your README here. 

What will be the best way to prevent `vinegar` from snatching `fugitive`?

**Comment by tpope** [comment]
That shouldn't happen. Check what `:verbose nmap -` reports.

**Comment by iamdionysus** [comment]
Strangely, I can't reproduce the situation. When I get the situation 
and I can reproduce it, I'll report the issue with the `:verbose nmap -` result. 
Anyway, here is the `:verbose nmap -` and it looks like it can't happen.

```
n -    *@:<C-U>silent execute <SNR>30_StageToggle(line('.'),line('.')+v:count1-1)<CR>
    Last set from ~\.vim\plugged\vim-fugitive\plugin\fugitive.vim
n -      <Plug>VinegarUp
    Last set from ~\.vim\plugged\vim-vineger\plugin\vinegar.vim
```

Sorry for bothering you and thanks a lot!

**Comment by iamdionysus** [comment]
It happens in `Gcommit` buffer not in `Gstatus`. The `Gstatus` buffer shows the same result as above. I'm using Vim 7.4 with 1-789 and vim-plug for plugin management. `:verbose nmap -` shows this.

```
n -        <Plug>VinegarUp
            Last set from ~\.vim\plugged\vim-vinegar\plugin\vinegar.vim
```

**Comment by tpope** [comment]
`:Gcommit` doesn't have a custom `-` map so sounds like everything is working as expected?

**Comment by iamdionysus** [comment]
I got it. I often go to `:Gcommit` and try to add untracked files there with `-`. Now I know how things are working, I'll adjust myself to it. I really appreciate your help to take a look at this. Thanks!

**Comment by trysten** [comment]
I think this issue can be closed. Do you mind if I review other open issues for the same?

**Comment by tpope** [comment]
> I think this issue can be closed. Do you mind if I review other open issues for the same?

Yes please. I didn't see this due to a GitHub notifications bug. :(
