### ISSUE TITLE
Issue with splits

### ISSUE THREAD

**Issue by zenazn** [tpope/vim-vinegar#58]
I've managed to find a ~minimal reproducing test case for a really frustrating behavior I've seen recently with Vinegar: open `vim` in a directory, type `-` to enter vinegar, select a file, run `<C-w>v` to split the screen, run `<C-w>l` to change to the new split, type `-` to enter vinegar in the split. What happens for me when I run the above is that vinegar opens as expected, but I am jumped back (?) to the first (left) split, and am unable to switch into the new (right, vinegar) split any more. I *am*, however, able to close the old (left) split, causing the new (right) split to regain focus, however the behavior after that point the bug is somehow "sticky": splitting the vinegar screen further and opening files again results in me being unable to use any of the ordinary `<C-w>` keystrokes to switch to the vinegar pane.

I'm running:
```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  2 2015 22:38:51)
MacOS X (unix) version
Included patches: 1-903
Compiled by Homebrew
```

I've reproduced this with a very minimal `vimrc` and have disabled the remainder of my pathogen bundles, so I don't *think* this is a bad interaction between plugins (although happy to provide more debugging information there if useful).

**Comment by tpope** [comment]
And what happens if you try without vinegar, using `:e %:h` where `-` doesn't exist?

**Comment by zenazn** [comment]
Fascinating. Tried that without vinegar and it still breaks.

Any suggestions on where to file this one? Against `vim` itself?

**Comment by zenazn** [comment]
Looks like this is a bug in netrw; will file a bug there. Thanks for your help!

**Comment by gotcha** [comment]
@zenazn Can you file here where the bug report URL ? I'd like to follow it.

**Comment by zenazn** [comment]
Unfortunately as best I can tell the `netrw` maintainer accepts bug reports at a personal email address.

**Comment by gotcha** [comment]
@zenazn To which email address did you report that bug ?

**Comment by zenazn** [comment]
The one at the bottom of `netrw-debug`

**Comment by zenazn** [comment]
The bug in `netrw`, by the way, is the newly-added `rexposn` feature (i.e., restore-position-for-Rexplore). The relevant code reads something like this:

```
 " If there is a rexposn: restore position with rexposn
 " Otherwise            : set rexposn
 if exists("s:rexposn_".bufnr("%"))
  NetrwKeepj call netrw#RestorePosn(s:rexposn_{bufnr('%')})
 else
  NetrwKeepj call s:SetRexDir(a:islocal,b:netrw_curdir)
 endif
```

And the bug (as best I can tell) is that `netrw` keeps track of `bufnr` but not `tabpagenr` or `winnr`. You can comment out that block above (or thread `tabpagenr` and `winnr` through in every callsite) to fix it.

**Comment by adamalbrecht** [comment]
I've also been experiencing this recently and it's been driving me crazy.

@zenazn Where can I find that code in order to comment it out? And does it require re-compiling vim? Thanks for your help!

**Comment by zenazn** [comment]
It's in `/usr/local/share/vim/vim74/autoload/netrw.vim` for me. No re-compiling needed!

**Comment by mnarrell** [comment]
Outstanding @zenazn!  Thanks so much

**Comment by OpakAlex** [comment]
thanks!

**Comment by gotcha** [comment]
@zenazn Did you communicate what you understood to Netrw developers ?

**Comment by zenazn** [comment]
I did—though let me follow up with them now.

**Comment by zenazn** [comment]
As an update, it looks like this bug has been fixed in the current alpha version of netrw (http://www.drchip.org/astronaut/vim/index.html#NETRW).

**Comment by mcandre** [comment]
New Vim user here, can I update my netrw version with Vundle, or will I have to wait for a new Vim release such as on Homebrew?

**Comment by ironhouzi** [comment]
@zenazn Did you notice a netrw regression recently?

I've not seen this bug in a long time, but it reemerged after upgrading vim to 7.4-1797. Would love to see this bug removed, even if it's just a dirty work-around.
