### ISSUE TITLE
Not ignoring wildignore directories

### ISSUE THREAD

**Issue by trevordmiller** [tpope/vim-vinegar#61]
@tpope: One of the main reasons I like the vinegar addition on top of vanilla netrw is for the "The oddly C-biased default sort order and file hiding is replaced with a sensible application of 'suffixes' and 'wildignore'." This works great for the file types I have in my `wildignore`, but it is not working for me with directory types:
![netrw-vinegar-wildignore](https://cloud.githubusercontent.com/assets/5497885/12008965/5aaccf6a-ac21-11e5-8562-c65054dc88c0.png)

p.s. I love vinegar and your other vim plugins; thank you for all you have done for the community!

**Comment by tpope** [comment]
So I'm sure some janky fuzzy finder is handling `'wildignore'` the way you expect, but vinegar is handling it the same way Vim itself does:

    :set wildignore=*/.git/*
    :echo glob('.gi*')
    .git

More to the point, `'wildignore'` was designed to ignore build artifacts that you would never, ever, ever load into Vim, while your usage suggests "things I don't typically want completed," and this semantic is not merely pedantic but one with real consequences. If Vinegar was "fixed" to do what you mean in this case, it would mean pressing `-` twice in `.git/config` (a perfectly reasonable file to edit) would have nowhere to land in the parent directory. And don't get me started on the consequences this will have for plugins like Fugitive, let alone builtin behaviors. So your feature request is really a bug request.

And the end goal of "lie to me in my directory list"? This is almost as ridiculous as patching `ls` itself to do the same.

**Comment by trevordmiller** [comment]
@tpope: Oh ok. I didn't realize that. No need to be rude about it. Thanks for explaining.

**Comment by tpope** [comment]
Blunt but not rude IMHO
