### ISSUE TITLE
"set splitright" causes vim-vinegar to get confused about splits

### ISSUE THREAD

**Issue by florianbeer** [tpope/vim-vinegar#62]
I've just found out that I had "splitright" set in my .vimrc which caused vim-vinegar to behave quite strangely.

Whenever I opened a new vertical split (which appeared to the right of my current buffer) and pressed "-" afterwards, it caused the cursor to jump back to the leftmost split (housing the buffer I was in before opening a new split) and I was unable to select the right split afterwards. Just to be clear, netrw was opened but it now resided in a split I couldn't navigate to. Only closing the leftmost split allowed me to operate in the netrw split again.

Removing "splitright" fixed said problem for me.

**Comment by gotcha** [comment]
@florianbeer Is this a duplicate of #58 ?

**Comment by florianbeer** [comment]
@gotcha You're right!
I'm sorry, I searched but couldn't find anything related to the bug.
Thanks for pointing it out!
