### ISSUE TITLE
Don't unconditionally override '-' mapping

### ISSUE THREAD

**Issue by dbarnett** [tpope/vim-vinegar#63]
Vinegar overrides the '-' mapping unless it detects another mapping already on '-'. I don't have any custom mapping but I want to use vim's default mapping. Apparently my only option is to override the built-in mapping with a version of itself or not install vinegar / hack the vinegar source locally.

**Comment by tpope** [comment]
Mapping to itself seems adequate enough to me. What are you suggesting instead?

**Comment by dbarnett** [comment]
Making the global mapping opt-in. It's weird to have plugins override misc vim behavior as a side-effect and even weirder to have everyone who wants to not lose default - map - to itself. At least the plugin should have docs with a heads-up and workaround.

**Comment by tpope** [comment]
It's documented prominently. It's the flagship feature so it definitely won't be changing to opt-in.

**Comment by suewonjp** [comment]
Hi

At least, can you let users override this behavior? 

If you change the code inside vim-vinegar.vim like so:

```
if exists("g:vinegar_up_mapping")
  exe "nmap " . g:vinegar_up_mapping  . " <Plug>VinegarUp"
else
  if empty(maparg('-', 'n'))
    nmap - <Plug>VinegarUp
  endif
endif
```
And if users define the variable in their local .vimrc like so:

    let g:vinegar_up_mapping='<leader>-'

They can override it. (Some people want to use Vim's default mapping for `-` which lets you go to previous lines)

And people liking Vim-vinegar's convention don't have to do anything.

**Comment by tpope** [comment]
You can achieve the same effect with

```viml
nmap <Leader>- <Plug>VinegarUp
nnoremap - -
```

**Comment by suewonjp** [comment]
Yes. That way is a lot preferable. No need to change the code.

But I think documenting about the workaround is necessary because nobody will come up with that without reading the plugin's code; No one will know what `<Plug>VinegarUp` is :-)

thanks
