### ISSUE TITLE
Pressing '-' twice doesn't work with latest Netrw

### ISSUE THREAD

**Issue by yous** [tpope/vim-vinegar#64]
I've tested with Netrw v155h, updated Jan 11, 2016 (http://www.drchip.org/astronaut/vim/index.html#NETRW). You can browse the source [here](https://github.com/yous/dotfiles/tree/1f37a2f5a77be59bda5c8a97963a9c3fb4a68c56/vim/bundle/netrw) directly.

The problem with this netrw.vim can be reproduced by simply pressing `-` key twice.

```
Error detected while processing function <SNR>31_opendir:
line    7:
E21: Cannot make changes, 'modifiable' is off: :<C-U>call <SNR>96_NetrwBrowseUpDir(1)
```

I think this is caused by `execute s:netrw_up` while `s:netrw_up` starts with `:<C-U>`. Also, `<C-U>` is the difference between the map of `-` in my `/usr/local/share/vim/vim74/autoload/netrw.vim` and in the latest `autoload/netrw.vim`. This is what the former have:

``` vim
nnoremap <buffer> <silent> <nowait> -        :call <SID>NetrwBrowseUpDir(1)<cr>
```

while [the latter](https://github.com/yous/dotfiles/blob/1f37a2f5a77be59bda5c8a97963a9c3fb4a68c56/vim/bundle/netrw/autoload/netrw.vim#L5964) have:

``` vim
nnoremap <buffer> <silent> <nowait> -	:<c-u>call <SID>NetrwBrowseUpDir(1)<cr>
```

**Comment by tpope** [comment]
Blind fix attempt incoming.

**Comment by yous** [comment]
It works seamlessly. Thanks for your quick response!
