### ISSUE TITLE
vinegar *maybe* breaks on Ubuntu 16 when splitting

### ISSUE THREAD

**Issue by killtheliterate** [tpope/vim-vinegar#67]
Noticed some strange behavior when using vim splits on Ubuntu 16 (haven't had the issue on OSX). When I split the window that becomes visible when pressing `-` and then open a file in one of the splits, the other split can no longer be navigated to. I'm not sure if this is a netrw thing, or a vim-vinegar thing, but I've been trying to isolate the issue. Right now, I'm using a vimrc that only contains vim-plug and vim-vinegar.

This is happening with neovim, haven't tested with vim yet.

GIVEN I have a file open in vim
AND I hit `-` to see the netrw thingy
WHEN I split the vim window with `:sp`
AND open a file from netrw in one of the splits
THEN I can no longer use `ctrl-w` to navigate to the other split

**Comment by srustamo** [comment]
See [here](https://github.com/tpope/vim-vinegar/issues/39) for more background.

**Comment by killtheliterate** [comment]
Ah, thanks.
