### ISSUE TITLE
Why *.h files are grayed out in vim-vinegar by default?

### ISSUE THREAD

**Issue by zealotrush** [tpope/vim-vinegar#78]
As shown in the following picture, the `hello.h` header file is grayed-out. It's really inconvenient for C developers. How can I customize this behavior? Thank you!

![vim-vinegar](https://cloud.githubusercontent.com/assets/2275580/20507773/dff62bbe-b097-11e6-88c7-f72659b4728d.png)

*GVim 8.0, Windows 7*

**Comment by tpope** [comment]
The default `'suffixes'` is pretty dumb. Try `:set suffixes-=.h`.
