### ISSUE TITLE
Going back?

### ISSUE THREAD

**Issue by Fiedzia** [tpope/vim-vinegar#81]
Stupid question: I pressed "-", file list opens, I decided I want to go back to my previous file, how do I do that?

**Comment by tpope** [comment]
`<C-O>` or `<C-^>`.

**Comment by nedclimaterisk** [comment]
Could that perhaps be added to the readme? It it from netrw? I can't find it in the docs.

**Comment by gotcha** [comment]
@nedclimaterisk This is Vim jump list : https://github.com/vim/vim/blob/master/runtime/doc/motion.txt#L1031
