### ISSUE TITLE
., !, y. commands for tree view not working correctly

### ISSUE THREAD

**Issue by suewonjp** [tpope/vim-vinegar#85]
When you use tree view, commands like ., !, y. produces `./\|\` in front of the file path.

```
| www/
| .DS_Store
| .eslintrc.js 
| .gitignore <--- your cursor is here
```

And you press . (period), you get the following output

`: ./\|\ .gitignore`

Is this a known behavior?

Anyway, I think the output should be consistent regardless of view styles

**Comment by IamCarbonMan** [comment]
Is there any intention to work on this? I'm encountering this issue and frankly it's very irritating.

**Comment by tpope** [comment]
I imagine a simple regexp tweak would do the trick.

**Comment by IamCarbonMan** [comment]
it would be really helpful to fix this. vinegar is extremely useful as a drawer in addition to using it in the file editor window itself.

**Comment by tpope** [comment]
I take it back, it'll take more than a regexp because we'll need to determine all the parent directories. Maybe netrw provides a function we could call?

**Comment by IamCarbonMan** [comment]
If it does, it's not in the [vimdoc](http://vimdoc.sourceforge.net/htmldoc/pi_netrw.html).

**Comment by SamTebbs33** [comment]
Is there an update on this? If not I'd be happy to address the issue given some guidance.

**Comment by tpope** [comment]
You'll need to write a function that takes

vim-vinegar/
| doc/
| plugin/
| | vinegar.vim

And turns it into `vim-vinegar/plugin/vinegar.vim`.

**Comment by patrickpichler** [comment]
@tpope wouldn't a function stripping the leading `| ` be enought? It might still fail for directories/files called `| file` but I expect this to be an edge case.

**Comment by tpope** [comment]
I blindly merged, but no, I would not expect that to cover most use cases.
