### ISSUE TITLE
The VinegarUp mapping should accept a count

### ISSUE THREAD

**Issue by zmughal** [tpope/vim-vinegar#86]
For example:

- `1-` : up 1 directory,
- `2-` : up 2 directories,
- `N-` : up N directories

**Comment by Gracecr** [comment]
As I'm trying it right now, this seems to be the case. Is this not your experience @zmughal ?

**Comment by tpope** [comment]
Same here, count works correctly for me.

**Comment by zmughal** [comment]
I compiled [Vim v8.0.1283](https://github.com/vim/vim/releases/tag/v8.0.1283) from Git and ran Vim using `vimrc_example.vim` and the [latest `vinegar.vim`](https://github.com/tpope/vim-vinegar/commit/c795cb739347cbddeeb288c3c35da9f140a513c9) (after patching with <https://github.com/tpope/vim-vinegar/issues/87#issuecomment-343347094>).

I can confirm that `1-`, `2-`, and `3-` work as expected. However counts >= 4 give the following error:

```
Error detected while processing function <SNR>20_opendir:
line    7:
E16: Invalid range: call <SNR>25_NetrwBrowseUpDir(1)
E16: Invalid range: call <SNR>25_NetrwBrowseUpDir(1)
```

with the number of "Invalid range" errors increasing as the count is increased.

**Comment by zmughal** [comment]
I can no longer reproduce this, so it is probably no longer a bug. Closing.
