### ISSUE TITLE
Entering vim-vinegar changes clipboard to `../`

### ISSUE THREAD

**Issue by louwers** [tpope/vim-vinegar#90]
With `set clipboard=unamedplus`, vim-vinegar modifies my clipboard when entering it. It changes the clipboard to `../`. Very strange behavior. For now I put `set clipboard=` in `.vim/ftplugin/netrw.vim`.

**Comment by daryllxd** [comment]
+1!

**Comment by louwers** [comment]
@daryllxd Glad I'm not the only one. Pretty sure it's vim-vinegar then.

**Comment by alexs95** [comment]
+1

**Comment by tpope** [comment]
Assuming this is a netrw bug until demonstrated otherwise.

**Comment by louwers** [comment]
@tpope When disabling vin-vinegar the problem goes away.
