### ISSUE TITLE
Last update on mac os seems to have borked yanking navigating and pasting to a different file.

### ISSUE THREAD

**Issue by dsalazar32** [tpope/vim-vinegar#97]
@tpope long time fan and follower of your work circa Hashrocket days.  It seems like the last mac update messes with the following vi workflow: yanking (yy) content from one file -> navigating via vinegar to another -> and pasting (p).  Nothing happens other than creating a new empty line.  Very strange behavior.  Below find the installed versions of OS, Terminal, and Plugins.  Hope it's helpful.

Versions installed:
OS: macOS High Sierra (Version 10.13.4)
Terminal: Iterm2 (build 3.1.6)
- ctrlp.vim
- node
- rust.vim
- vim-airline
- vim-airline-themes
- vim-bundler
- vim-fugitive
- vim-go
- vim-jsx
- vim-rails
- vim-sensible
- vim-surround
- vim-terraform
- vim-toml
- vim-unimpaired
- vim-vinegar (latest pull)

Hope this is helpful.  Cheers.

**Comment by tpope** [comment]
Have you tried with bare Netrw?

**Comment by tpope** [comment]
Try turning the banner back on with `let g:netrw_banner = 1`. There seem to be a lot of Netrw quirks when you turn it off.

**Comment by t0str** [comment]
I have the same problem as OP (`macos 10.14.6/neovim --HEAD`). Turning banner on fixes the problem. So this bug should be reported against netrw?

**Comment by tpope** [comment]
Yes please!
