### ISSUE TITLE
Respect 'autowrite' in the - map

### ISSUE THREAD

**Issue by odnoletkov** [tpope/vim-vinegar#98]
Currently if I try to `-` out of modified buffer I get
```
Error detected while processing function <SNR>40_opendir:
line   12:
E37: No write since last change (add ! to override)
```
`'autowriteall'` can fix this but it is too much. Switching to Netrw seems to fit naturally in the list of actions `'autowrite'` covers.

On the other hand there is a bizarre behaviour of `:Explore` which opens new split if buffer is modified…

**Comment by tpope** [comment]
I don't know, I'm kind of the mind that it shouldn't be possible to write the file by accidentally bumping a single key.

**Comment by odnoletkov** [comment]
Makes sense. Given that one can config around this it’s not a big deal.
