### ISSUE TITLE
Hitting '-' triggers Space hit.

### ISSUE THREAD

**Issue by 010penetrator** [tpope/vim-vinegar#99]
In vimrc:
```
nnoremap <Space> :colo blue<CR>
```
When I press minus in netrw, vim goes blue.

**Comment by 010penetrator** [comment]
Originally my <Space> bind action included a variable declared in Vimrc and I had 'undefined variable' error every time I leveled up in netrw.

**Comment by tpope** [comment]
Add `let g:netrw_up = s:netrw_up` after https://github.com/tpope/vim-vinegar/blob/b06c3df86bf581e12dab39ac94ddd5ad976b16ca/plugin/vinegar.vim#L102 and see what the value of that variable is.

**Comment by 010penetrator** [comment]
netrw_up is <Plug>NetrwBrowseUpDir

If I remove netrw from Vundle list that changes to
 <C-U>call <SNR>71_NetrwBrowseUpDir(1)<CR>
and problem is not present.
So not a Vinegar bug I guess.

**Comment by tpope** [comment]
I was wrong. Netrw itself includes a space in the map. See https://github.com/eiginn/netrw/blob/72f12d8707e01f36308149e55007538bae02542f/autoload/netrw.vim#L6313. Report it to the maintainer. I'm rolling my change back because it has other problems.
